extends Node

signal refund
signal speed_upgrade
signal bullet_delay_upgrade
signal add_laser
signal plasma_lasers

var shooting_speed_tier
var ship_speed_tier
var double_lasers

func _ready():
	pass

#func _process(delta):
#	pass


func _on_Button_pressed():
	get_tree().paused = false
	queue_free()


func _on_Refund_pressed():
	get_tree().paused = false
	emit_signal("refund")
	$ShootingSpeedIcon.frame = 0
	pass # replace with function body

func shooting_speed_upgrade_success():
	$ShootingSpeedIcon.frame += 1

func _on_ShootingSpeedUpgrade_pressed():
	get_tree().paused = false
	emit_signal("bullet_delay_upgrade")
	$ShootingSpeedIcon.frame += 1
	pass